/*
 * environ.h
 *
 * Generated by configure
 *
 */

#ifndef _TYPHOON_ENVIRON_H
#define _TYPHOON_ENVIRON_H

#define CREATMASK 0666
#define O_BINARY  0
#define DIR_SWITCH '/'
#ifndef offsetof
#define offsetof(s,m) ((int)&(((s *)0))->m)
#endif
#if defined(sparc) || defined(mips) || defined(HPUX) || defined(__alpha)
#define RISC 1
#endif
#define UNIX 1
#ifdef LITTLE_ENDIAN
#undef LITTLE_ENDIAN
#endif /* LITTLE_ENDIAN */
#define LITTLE_ENDIAN 1

#define PROTOTYPES 1
#define PRM(x)   x
#define _PRM(x)  x
#define ELLIPSIS ,...


typedef unsigned char uchar;
typedef unsigned short ushort;
typedef unsigned long ulong;

#endif
/* end-of-file */
